# pnpm 10+ uses allowBuilds instead of onlyBuiltDependencies
# This allows packages to run their postinstall/build scripts
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  sharp: true
  unrs-resolver: true
  esbuild: true
